toml-version = "v1.1.0"

[format.rules]
comment-style = "preserve"
date-time-delimiter = "preserve"
indent-width = 4
key-quote-style = "preserve"
string-quote-style = "preserve"

[[schemas]]
path = "tombi://www.schemastore.org/cargo.json"
include = ["Cargo.toml", "**/Cargo.toml"]

[schemas.format.rules]
array-values-order.enabled = false
table-keys-order.enabled = false

[[schemas.overrides]]
targets = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "workspace.dependencies",
    "target.*.dependencies",
    "target.*.dev-dependencies",
    "target.*.build-dependencies",
]
format.rules.table-keys-order = "ascending"
